### ISSUE TITLE
room member information is incomplete

### ISSUE THREAD

**Issue by zhaokefei** [lijiarui/wechaty-puppet-padchat#124]
**sometime cannot get member nickname and gender information**

![image](https://user-images.githubusercontent.com/16509241/43383635-336a44f0-940e-11e8-99fd-7c3c9b005faa.png)

related issue: #98

**Comment by windmemory** [comment]
Hi @zhaokefei ,

Could you please provide more information about this issue so we can debug this :)

Thanks

**Comment by lijiarui** [comment]
### Need More Information

Sorry, you did not follow the **ISSUE Template**, and there's not enough information about your problem.

In order to help us to find the problem out, you should provide all the detail information about the issue. Please make sure you are following the ISSUE Template, answer all the question, and the more important: **provide the steps to reproduce the problem**.

I'll close this issue. Please re-submit a new issue to provide the information that needed.
