### ISSUE TITLE
the mobile terminal logs out and the service is interrupted

### ISSUE THREAD

**Issue by zhaokefei** [lijiarui/wechaty-puppet-padchat#170]
![image](https://user-images.githubusercontent.com/16509241/44965393-ec8dac00-af67-11e8-98ef-9b012c31f05b.png)

@windmemory

**Comment by lijiarui** [comment]
### Need More Information

Sorry, you did not follow the **ISSUE Template**, and there's not enough information about your problem.

In order to help us to find the problem out, you should provide all the detail information about the issue. Please make sure you are following the ISSUE Template, answer all the question, and the more important: **provide the steps to reproduce the problem**.

I'll close this issue. Please re-submit a new issue to provide the information that needed.
