### ISSUE TITLE
首次调用Contact.say接口后无法同步Contact消息

### ISSUE THREAD

**Issue by ftfuntjh** [lijiarui/wechaty-puppet-padchat#180]
当在message事件中调用contact.say接口后无法同步contact消息
``` javascript
const Instance = new Wechaty({puppet,name});
await Instance.ready();
Instance.on('message',async(message)=>{
    await message.from().say("emmmmmm");
});
```
//此处会报错
```shell
26|npm     | Error: no raw payloadwxid_wk54b3cj2qxh12
26|npm     |     at PadchatManager.<anonymous> (/root/code/wechaty/node_modules/wechaty-puppet-padchat/src/padchat-manager.ts:1055:13)
26|npm     |     at Generator.next (<anonymous>)
26|npm     |     at fulfilled (/root/code/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-manager.js:4:58)
26|npm     |     at process._tickCallback (internal/process/next_tick.js:68:7)
//无法完成消息同步 此后机器人只能收到heartbeat

```

**Comment by lijiarui** [comment]
### Need More Information

Sorry, you did not follow the **ISSUE Template**, and there's not enough information about your problem.

In order to help us to find the problem out, you should provide all the detail information about the issue. Please make sure you are following the ISSUE Template, answer all the question, and the more important: **provide the steps to reproduce the problem**.
