### ISSUE TITLE
无法发送图片

### ISSUE THREAD

**Issue by WellJay** [lijiarui/wechaty-puppet-padchat#189]
![avatar](http://static.fangzhoubuluo.com/bug.png)

没进filebox的if，直接走进了最后的else 抛异常

**Comment by WellJay** [comment]
"file-box": "^0.8.24",
    "puppet-padchat-patch": "^0.1.11",
    "wechaty-puppet-padchat": "^0.17.15",

**Comment by lijiarui** [comment]
### Need More Information

Sorry, you did not follow the **ISSUE Template**, and there's not enough information about your problem.

In order to help us to find the problem out, you should provide all the detail information about the issue. Please make sure you are following the ISSUE Template, answer all the question, and the more important: **provide the steps to reproduce the problem**.

I'll close this issue. Please re-submit a new issue to provide the information that needed.
