### ISSUE TITLE
接口断线的解决办法

### ISSUE THREAD

**Issue by zhaizong** [lijiarui/wechaty-puppet-padchat#191]
用户出现了推送异常的情况，希望有一个解决方案

**Comment by kis87988** [comment]
docker or npm?

**Comment by lijiarui** [comment]
### Need More Information

Sorry, you did not follow the **ISSUE Template**, and there's not enough information about your problem.

In order to help us to find the problem out, you should provide all the detail information about the issue. Please make sure you are following the ISSUE Template, answer all the question, and the more important: **provide the steps to reproduce the problem**.

I'll close this issue. Please re-submit a new issue to provide the information that needed.
