### ISSUE TITLE
运行一段时间之后自动退出 

### ISSUE THREAD

**Issue by typedef** [lijiarui/wechaty-puppet-padchat#196]
08:49:59 WARN PuppetPadchat messageFile(847380361315305688)
### 1
/wechaty/bin/entrypoint.sh: line 179:    26 Killed                  BABEL_DISABLE_CACHE=1 babel-node --presets @babel/env "$@"
ERROR: Bot exited with code 137

**Comment by lijiarui** [comment]
### Need More Information

Sorry, you did not follow the **ISSUE Template**, and there's not enough information about your problem.

In order to help us to find the problem out, you should provide all the detail information about the issue. Please make sure you are following the ISSUE Template, answer all the question, and the more important: **provide the steps to reproduce the problem**.

I'll close this issue. Please re-submit a new issue to provide the information that needed.
